<a href="https://colab.research.google.com/github/Fdark18/Portifolio/blob/main/Aprender_indexa%C3%A7%C3%A3o_e_fatiamento_(slicing)_de_matrizes_no_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Aprender indexação e fatiamento (slicing) de matrizes no Python

In [ ]:
q = [1,2,3,4,5,6,7]
q[1]
q[0]

1

In [ ]:
q[0:4]

[1, 2, 3, 4]

In [ ]:
q[0:4] + q[4:]

[1, 2, 3, 4, 5, 6, 7]

In [ ]:
q[:] #omitir os dois começos fazendo com que seja imprimido a lista completa

[1, 2, 3, 4, 5, 6, 7]

In [ ]:
a = q[1:].copy() #copidando alista para uma nova variavel
a[:]

[2, 3, 4, 5, 6, 7]

In [ ]:
a[::2] # Imprimir a lista inteira e os 2 dois ponto(:: 2) quer dizer de quantos deve pular pra imprimir
        #no  caso numa lista de [1,2,3,4,5,6,7] imprimira 2,4,6


[2, 4, 6]

# Para reverter a orndem


In [ ]:
a[::-1]


[7, 6, 5, 4, 3, 2]

# **ou**

In [ ]:
# Para reverter um string
'1,2,3,4,5' [::-1]

'5,4,3,2,1'

In [ ]:
dias_semana = ["segunda", "terça", "quarta", "quinta", "sexta", "sábado", "domingo"]
ultimos_tres_dias = dias_semana[-3:]
print(ultimos_tres_dias)  # Saída: ["sexta, sábado", "domingo"]


['sexta', 'sábado', 'domingo']


** [4 5 6]]
O fatiamento também pode incluir reticências (…) para fazer uma tupla de seleção do mesmo comprimento que a dimensão de uma matriz. Se reticências forem usadas na posição da linha, ele retornará um ndarray composto de itens nas linhas.**

In [ ]:
# Iniciando uma matriz
import numpy as np
a = np.array([[1,2,3],[4,5,6],[6,7,8]])

In [ ]:
print ('Nossa matrix é:')
print (a)

Nossa matrix é:
[[1 2 3]
 [4 5 6]
 [6 7 8]]


In [ ]:
# Este retornará uma matriz de intens da segunda coluna
print ("Os itens da segunda coluna são:")
print(a[...,1])

Os itens da segunda coluna são:
[2 5 7]


In [ ]:
# Agora iremos fatiar  todos os itens da segunda linha
print('Os itens da segunda linha são:')
print (a[1,...])


Os itens da segunda linha são:
[4 5 6]


In [ ]:
# Agora iremos fatiar todos os itens da coluna 1 adiante
print('Os itens da coluna 1 em diante são:')
print(a[...,1:])

Os itens da coluna 1 em diante são:
[[2 3]
 [5 6]
 [7 8]]


# **iNDETIFICAR SE UMA PALAVRA É PALINDROMO**

In [ ]:

palavra = 'radar'
if palavra == palavra[::-1]: # Verificando se palavra é igual palavra de trás para frente.
  print('Palindromo!')
else:
  print('Não é palindromo!')


Não é palindromo!
